version: "3.8"
services:
  backend:
    container_name: app-backend
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
  database:
    container_name: app-db
    image: mongo
    ports:
      - "27017:27017"
  client: 
    container_name: app-frontend 
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - database 
      - backend 